### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SRowick** [Whimfoome/godot-InventorySystem#1] opened 2020-07-30 07:40 UTC
Hi, very cool inventory system but the program crashes when reopening the inventory after having eaten a mushroom, and also if you eat an apple that is inbetween two other apples (making a blank space inbetween).

I am using v3.2.1.stable.mono.official

**Comment by Whimfoome** [comment] 2020-07-30 08:54
Sorry, I don't experience the problem you are describing. Try doing it with the latest version of Godot 3.2.3-rc2 and tell me if you still are experiencing this issue with more detail and the error message. Also if you are rewriting this in C#, after `QueueFree()` an Item you need to set it to null (In GDScript it happens automatically).

**Comment by Alec-15** [comment] 2021-06-16 14:04
I have the same issue.

To reproduce:
Start game
Open Backpack
Fill with 3 mushrooms
Consume middle mushroom
Close Backpack
Open Backpack

Error:
E 0:00:26.123   call_ptr: Attempted method call on a deleted object.
  <C++ Source>  core/variant_call.cpp:1142 @ call_ptr()
  <Stack Trace> InventoryComponent.gd:134 @ toggle_window()
                Player.gd:11 @ _input()


Using v3.3.2.stable.official

**Comment by Alec-15** [comment] 2021-06-16 15:03
If think the issue is something else.
You just need to open and close backpack twice to get this effect.
When I print out the window_ref in line 122 I get:
`window_ref: [Deleted Object]`

So line 122 should be changed to:
`if not is_instance_valid(window_ref):`
That solves the problem

**Comment by Whimfoome** [comment] 2021-06-16 18:30
@Alec-15 Thanks for letting me know! This is something new, probably from version 3.3 or newer, because this hadn't happened before. Will push a fix soon! Again thanks!

**Comment by Whimfoome** [comment] 2021-06-16 18:53
@Alec-15 Okay, should be fixed now! Please try the latest commit [01bf96b](https://github.com/Whimfoome/godot-InventorySystem/commit/01bf96b6092a96f78cade2238c880294cca48ab6) and see if you still get crashes.

**Closed as completed** 2022-11-25 11:16 UTC
Labels: bug
